import type { Metadata } from "next";
import { siteConfig } from "@/config/site";
import { LegalLayout, LegalHeading } from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Data Sources",
  description: `Where ${siteConfig.name}'s weather data comes from, attribution requirements, limitations and update frequency.`,
  alternates: { canonical: "/data-sources" },
};

export default function DataSourcesPage() {
  return (
    <LegalLayout title="Data Sources">
      <p>
        {siteConfig.name} does not measure weather or run its own forecast models. All forecast data shown on this site is sourced from
        third-party weather data providers through their public APIs. This page explains, transparently, where that data comes from and
        what its limitations are.
      </p>

      <LegalHeading>Demo mode</LegalHeading>
      <p>
        This build is currently running in <strong>demo mode</strong> ({`DEMO_MODE=true`}). All figures you see — temperatures, wind,
        precipitation probability, and so on — are generated by a deterministic sample-data engine for demonstration purposes only and
        do not reflect real weather conditions. Demo mode exists so the interface can be evaluated end-to-end before any provider
        contracts are signed. See the "Live providers" section below for what will replace it.
      </p>

      <LegalHeading>Live providers (when demo mode is disabled)</LegalHeading>
      <p>The architecture is built around three interchangeable comparison sources. As implemented today, they are:</p>
      <ul className="list-disc space-y-2 pl-5">
        <li>
          <strong>Provider A</strong> — OpenWeatherMap (openweathermap.org), classic free "Current Weather" and "5 Day / 3 Hour Forecast" endpoints (not the paid One Call 3.0 plan, which needs a card on file). Adapter:{" "}
          <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">lib/providers/openweather.ts</code>. Requires a free API key set as{" "}
          <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">SECOND_WEATHER_API_KEY</code>. Covers 5 days (in 3-hour steps) rather than 10, and doesn't provide alerts or UV index — WeatherAPI.com and Open-Meteo still do.
        </li>
        <li>
          <strong>Provider B</strong> — WeatherAPI.com (weatherapi.com), forecast.json. Adapter:{" "}
          <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">lib/providers/weatherapi.ts</code>. Requires a free API key set as{" "}
          <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">THIRD_WEATHER_API_KEY</code>.
        </li>
        <li>
          <strong>Provider C</strong> — Open-Meteo (open-meteo.com). Adapter:{" "}
          <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">lib/providers/meteomatics.ts</code>. No API key is required for the free, non-commercial tier — this provider activates automatically once demo mode is disabled. Open-Meteo has no alerts endpoint, so it never shows alerts.
        </li>
      </ul>
      <p>
        <strong>Before enabling any provider in production, you must independently verify its current commercial licensing, pricing,
        attribution requirements and rate limits directly with that provider.</strong> Terms change over time and are not reproduced or
        guaranteed here.
      </p>

      <LegalHeading>Attribution</LegalHeading>
      <p>
        Wherever live data from a provider is shown, the interface displays a "Source: [Provider Name]" label linking to that provider,
        in line with typical attribution requirements for weather APIs. If you swap or add a provider, keep this attribution pattern —
        see the <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">ForecastComparison</code> component.
      </p>

      <LegalHeading>Update frequency & caching</LegalHeading>
      <p>
        Forecast data is cached at the edge for a short period (currently 10 minutes, see the <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">Cache-Control</code> headers
        on <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">/api/providers/*</code>) to stay within provider rate limits and keep the site fast. This means displayed
        conditions may lag the very latest observation by a few minutes.
      </p>

      <LegalHeading>Limitations</LegalHeading>
      <p>
        Weather forecasts — from any provider — are estimates, not guarantees, and become less reliable further into the future.
        {" "}{siteConfig.name} does not claim that any single provider, or the comparison itself, is guaranteed to be accurate. For
        official warnings and life-safety decisions, always consult your national meteorological service.
      </p>

      <LegalHeading>Maps</LegalHeading>
      <p>
        The Weather Map section on each city page is a real, interactive map (pan/zoom, OpenStreetMap base layer) with a marker for that
        city. Live temperature, precipitation, wind and cloud-cover tile overlays are powered by OpenWeatherMap's map tile service, and
        activate automatically once <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">NEXT_PUBLIC_OWM_MAP_KEY</code> is set (the satellite layer, from Esri's public World Imagery service, needs no key
        and is always available). Without that key, the map still shows the real location — just without the live weather overlays.
      </p>
    </LegalLayout>
  );
}
