/**
 * Long-term monthly climate averages per city, generated by
 * scripts/fetch-climate.mjs from daily data for 2011–2020: NASA POWER for most
 * cities, ERA5 (via Open-Meteo) for the coastal/island cities listed under
 * "era5" in climate.json. Re-run that script whenever cities are added to
 * config/countries.ts.
 *
 * Every consumer must cope with a city having no data (script not yet run,
 * or a fetch failed) — pages for such cities are simply not generated.
 */
import climateJson from "./climate.json";
import { countries, type CountrySeed, type CitySeed } from "@/config/countries";

export interface CityClimate {
  /** Average daily high, °C, Jan..Dec */
  tMax: number[];
  /** Average daily low, °C */
  tMin: number[];
  /** Average monthly precipitation, mm */
  precipMm: number[];
  /** Average relative humidity, % */
  humidity: number[];
  /** Average cloud cover, % */
  cloud: number[];
}

interface ClimateFile {
  source: string;
  generatedAt: string;
  /** Cities sourced from ERA5 instead of NASA POWER, with an optional fixed elevation (m). */
  era5?: Record<string, { elevation: number | null; lat?: number; lon?: number; fetched?: string; kept?: "nasa" }>;
  cities: Record<string, CityClimate>;
}

const data = climateJson as ClimateFile;

export const CLIMATE_SOURCE = data.source;

export const MONTHS = [
  { slug: "january", name: "January", short: "Jan" },
  { slug: "february", name: "February", short: "Feb" },
  { slug: "march", name: "March", short: "Mar" },
  { slug: "april", name: "April", short: "Apr" },
  { slug: "may", name: "May", short: "May" },
  { slug: "june", name: "June", short: "Jun" },
  { slug: "july", name: "July", short: "Jul" },
  { slug: "august", name: "August", short: "Aug" },
  { slug: "september", name: "September", short: "Sep" },
  { slug: "october", name: "October", short: "Oct" },
  { slug: "november", name: "November", short: "Nov" },
  { slug: "december", name: "December", short: "Dec" },
] as const;

export type MonthSlug = (typeof MONTHS)[number]["slug"];

export function monthIndex(slug: string): number {
  return MONTHS.findIndex((m) => m.slug === slug);
}

export function getCityClimate(countrySlug: string, citySlug: string): CityClimate | null {
  return data.cities[`${countrySlug}/${citySlug}`] ?? null;
}

/** Every seed city that has climate data, with its data attached. */
export function citiesWithClimate(): Array<{ country: CountrySeed; city: CitySeed; climate: CityClimate }> {
  const out: Array<{ country: CountrySeed; city: CitySeed; climate: CityClimate }> = [];
  for (const country of countries) {
    for (const city of country.cities) {
      const climate = getCityClimate(country.slug, city.slug);
      if (climate) out.push({ country, city, climate });
    }
  }
  return out;
}

/** Days in each month, for turning monthly totals into rough daily figures. */
export const DAYS_IN_MONTH = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

/** Short plain-English label for how a month typically feels. */
export function describeMonth(c: CityClimate, i: number): { temp: string; rain: string; sky: string } {
  const high = c.tMax[i]!;
  const rain = c.precipMm[i]!;
  const cloud = c.cloud[i]!;
  const temp =
    high >= 32 ? "very hot" : high >= 27 ? "hot" : high >= 21 ? "warm" : high >= 15 ? "mild" : high >= 8 ? "cool" : high >= 2 ? "cold" : "freezing";
  const rainLabel = rain < 20 ? "very dry" : rain < 50 ? "fairly dry" : rain < 90 ? "some rain" : rain < 150 ? "wet" : "very wet";
  const sky = cloud < 35 ? "mostly sunny" : cloud < 55 ? "a mix of sun and cloud" : "often cloudy";
  return { temp, rain: rainLabel, sky };
}

/**
 * Monthly-highs map for CityGrid's mini charts, keyed "country/city".
 * Call on the server and pass the result down as a prop.
 */
export function climateHighsFor(items: Array<{ country: { slug: string }; city: { slug: string } }>): Record<string, number[]> {
  const out: Record<string, number[]> = {};
  for (const { country, city } of items) {
    const c = getCityClimate(country.slug, city.slug);
    if (c) out[`${country.slug}/${city.slug}`] = c.tMax;
  }
  return out;
}
