/**
 * Long-term monthly climate averages per city (2011–2020).
 *
 * Two files feed it:
 * - climate.json — the curated core cities, generated by
 *   scripts/fetch-climate.mjs (NASA POWER; ERA5 via Open-Meteo for the
 *   coastal/island cities listed under "era5").
 * - climate-world.json — the 1,700 world-dataset cities, NASA POWER daily
 *   data 2011–2020 averaged per month (same method), compact arrays.
 *   Rebuilt by scripts/world/ (see scripts/world/README.md).
 *
 * Every consumer must cope with a city having no data — pages for such
 * cities are simply not generated (and they stay out of the sitemaps).
 *
 * SERVER ONLY: client components import lib/data/months.ts instead.
 */
import climateJson from "./climate.json";
import worldClimateJson from "./climate-world.json";
import { countries, type CountrySeed, type CitySeed } from "@/config/world";
import type { CityClimate } from "./months";

export type { CityClimate } from "./months";
export { MONTHS, monthIndex, DAYS_IN_MONTH, describeMonth, type MonthSlug } from "./months";

interface ClimateFile {
  source: string;
  generatedAt: string;
  /** Cities sourced from ERA5 instead of NASA POWER, with an optional fixed elevation (m). */
  era5?: Record<string, { elevation: number | null; lat?: number; lon?: number; fetched?: string; kept?: "nasa" }>;
  cities: Record<string, CityClimate>;
}

interface WorldClimateFile {
  source: string;
  generatedAt: string;
  /** "country/city": [tMax×12, tMin×12, precipMm×12, humidity×12, cloud×12] */
  cities: Record<string, [number[], number[], number[], number[], number[]]>;
}

const data = climateJson as ClimateFile;
const world = worldClimateJson as unknown as WorldClimateFile;

const all: Record<string, CityClimate> = {};
for (const [key, [tMax, tMin, precipMm, humidity, cloud]] of Object.entries(world.cities ?? {})) {
  all[key] = { tMax, tMin, precipMm, humidity, cloud };
}
// Curated data wins (ERA5 for coasts, hand-checked).
Object.assign(all, data.cities);

export const CLIMATE_SOURCE = data.source;

export function getCityClimate(countrySlug: string, citySlug: string): CityClimate | null {
  return all[`${countrySlug}/${citySlug}`] ?? null;
}

let cache: Array<{ country: CountrySeed; city: CitySeed; climate: CityClimate }> | null = null;

/** Every city (core + world) that has climate data, with its data attached. */
export function citiesWithClimate(): Array<{ country: CountrySeed; city: CitySeed; climate: CityClimate }> {
  if (cache) return cache;
  const out: Array<{ country: CountrySeed; city: CitySeed; climate: CityClimate }> = [];
  for (const country of countries) {
    for (const city of country.cities) {
      const climate = getCityClimate(country.slug, city.slug);
      if (climate) out.push({ country, city, climate });
    }
  }
  cache = out;
  return out;
}

/** Well-known destinations only (core + featured), for "where to go" lists and the trip finder. */
export function featuredCitiesWithClimate() {
  return citiesWithClimate().filter((c) => c.city.core || c.city.featured || c.city.population >= 1_000_000);
}

/**
 * The trip finder ships its cities to the browser, so it gets a smaller set:
 * every core city plus the 300 largest well-known destinations (~140 kB).
 */
export function tripFinderCitiesWithClimate() {
  const all = citiesWithClimate();
  const core = all.filter((c) => c.city.core);
  const extra = all
    .filter((c) => !c.city.core && c.city.featured)
    .sort((a, b) => b.city.population - a.city.population)
    .slice(0, 300);
  return [...core, ...extra];
}

/**
 * Monthly-highs map for CityGrid's mini charts, keyed "country/city".
 * Call on the server and pass the result down as a prop.
 */
export function climateHighsFor(items: Array<{ country: { slug: string }; city: { slug: string } }>): Record<string, number[]> {
  const out: Record<string, number[]> = {};
  for (const { country, city } of items) {
    const c = getCityClimate(country.slug, city.slug);
    if (c) out[`${country.slug}/${city.slug}`] = c.tMax;
  }
  return out;
}
