/**
 * Every city and country the site has a page for: the curated core list in
 * config/countries.ts plus the world dataset in lib/data/world.json
 * (1,800+ cities in 200+ countries, generated by scripts/build-world.mjs).
 *
 * SERVER ONLY. Pages, route handlers and sitemaps import this; client
 * components must keep importing config/countries.ts (the small core list)
 * so the world dataset never ends up in the browser bundle.
 *
 * How the world list was chosen (see scripts/build-world.mjs):
 * - every country's capital, then cities by population weighted towards the
 *   markets the site serves (Spain first, Spanish-speaking Latin America,
 *   Europe), plus ~1,300 named holiday destinations;
 * - one city per NASA POWER grid cell (0.5° × 0.625°) and at least 25 km
 *   between cities, so no two pages share the same climate numbers;
 * - names and translations from GeoNames and Wikidata.
 */
import worldJson from "@/lib/data/world.json";
import { countries as coreCountries, type CountrySeed, type CitySeed } from "./countries";
import { registerPlaceNames } from "@/lib/i18n/places";

export type { CountrySeed, CitySeed };

/** [slug, name, region, lat, lon, population, timezone, flags, localized names?] */
type CityRow = [string, string, string, number, number, number, string, number, string[]?];

interface WorldFile {
  countries: Record<
    string,
    {
      /** English name */
      n: string;
      iso: string;
      /** Continent / region label used by the trip finder. */
      r: string;
      /** Localized names [it, de, fr, es, pt, nl, pl, tr] — only for countries not in places.ts. */
      l?: string[];
      c: CityRow[];
    }
  >;
}

const W = worldJson as unknown as WorldFile;

const REGION_BY_COUNTRY: Record<string, string> = {};
const cityNames: Record<string, string[]> = {};
const countryNames: Record<string, string[]> = {};

function build(): CountrySeed[] {
  const merged: CountrySeed[] = coreCountries.map((c) => ({
    ...c,
    cities: c.cities.map((city) => ({ ...city, core: true, featured: true })),
  }));
  const bySlug = new Map(merged.map((c) => [c.slug, c]));
  for (const [slug, wc] of Object.entries(W.countries)) {
    REGION_BY_COUNTRY[slug] = wc.r;
    if (wc.l && wc.l.length === 8) countryNames[slug] = wc.l;
    let country = bySlug.get(slug);
    if (!country) {
      country = { slug, name: wc.n, isoCode: wc.iso, cities: [] };
      merged.push(country);
      bySlug.set(slug, country);
    }
    for (const [cslug, name, region, lat, lon, population, timezone, flags, local] of wc.c) {
      country.cities.push({ slug: cslug, name, region, lat, lon, population, timezone, featured: (flags & 1) === 1 });
      if (local && local.length === 8) cityNames[cslug] = local;
    }
  }
  return merged;
}

/** All countries (core ones first, in their curated order), each with all its cities. */
export const countries: CountrySeed[] = build();
registerPlaceNames(cityNames, countryNames);

const cityIndex = new Map<string, { country: CountrySeed; city: CitySeed }>();
for (const country of countries) for (const city of country.cities) cityIndex.set(`${country.slug}/${city.slug}`, { country, city });

export function findCity(countrySlug: string, citySlug: string) {
  return cityIndex.get(`${countrySlug}/${citySlug}`) ?? null;
}

export function findCountry(countrySlug: string): CountrySeed | null {
  return countries.find((c) => c.slug === countrySlug) ?? null;
}

export function allCityPaths() {
  return countries.flatMap((country) => country.cities.map((city) => ({ country: country.slug, city: city.slug })));
}

/** Only the curated core cities: what gets pre-rendered at deploy time. Every
 * other city page is rendered on its first request and then cached (ISR). */
export function coreCityPaths() {
  return countries.flatMap((country) => country.cities.filter((c) => c.core).map((city) => ({ country: country.slug, city: city.slug })));
}

export function cityCount(): number {
  return cityIndex.size;
}

/** Region label ("Europe", "Asia", …) for the trip finder. */
export function worldRegionOf(countrySlug: string): string | undefined {
  return REGION_BY_COUNTRY[countrySlug];
}

const toRad = (d: number) => (d * Math.PI) / 180;
/** Great-circle distance in km. */
export function distanceKm(a: { lat: number; lon: number }, b: { lat: number; lon: number }): number {
  const dLat = toRad(b.lat - a.lat);
  const dLon = toRad(b.lon - a.lon);
  const h = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLon / 2) ** 2;
  return 2 * 6371 * Math.asin(Math.sqrt(h));
}

/**
 * The closest other cities with a page, nearest first — the backbone of the
 * internal links between the 1,800+ city pages (each page links to its
 * neighbours, so every page is reachable within a few clicks).
 */
export function nearestCities(
  from: CitySeed,
  limit = 6,
  opts: { sameCountry?: string; maxKm?: number } = {}
): Array<{ country: CountrySeed; city: CitySeed; km: number }> {
  const out: Array<{ country: CountrySeed; city: CitySeed; km: number }> = [];
  for (const country of countries) {
    if (opts.sameCountry && country.slug !== opts.sameCountry) continue;
    for (const city of country.cities) {
      if (city === from || (city.slug === from.slug && city.lat === from.lat)) continue;
      // cheap bounding-box reject before the trig
      if (Math.abs(city.lat - from.lat) > 25) continue;
      const km = distanceKm(from, city);
      if (opts.maxKm && km > opts.maxKm) continue;
      out.push({ country, city, km });
    }
  }
  return out.sort((a, b) => a.km - b.km).slice(0, limit);
}

/** Biggest cities of a country first (core cities keep their curated lead). */
export function citiesByImportance(country: CountrySeed): CitySeed[] {
  return [...country.cities].sort((a, b) => Number(!!b.core) - Number(!!a.core) || b.population - a.population);
}

export { localizedCityName, localizedCountryName } from "./countries";
